#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$project_dir/.env"
secret_dir="/etc/chesspit"
rotate_passwords=false
ssh_port_override=""
external_caddy_override=""
http_port_override=""

usage() {
  echo "Usage: sudo ./scripts/install-vps.sh [--rotate-passwords] [--ssh-port PORT] [--http-port PORT] [--external-caddy|--bundled-caddy]" >&2
}

while (( $# )); do
  case "$1" in
    --rotate-passwords)
      rotate_passwords=true
      shift
      ;;
    --ssh-port)
      if [[ -z "${2:-}" ]]; then
        usage
        exit 2
      fi
      ssh_port_override="$2"
      shift 2
      ;;
    --external-caddy)
      external_caddy_override=true
      shift
      ;;
    --http-port)
      if [[ -z "${2:-}" ]]; then
        usage
        exit 2
      fi
      http_port_override="$2"
      shift 2
      ;;
    --bundled-caddy)
      external_caddy_override=false
      shift
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done
if (( EUID != 0 )); then
  echo "Run this installer with sudo." >&2
  exit 1
fi
if [[ "$(uname -m)" != "x86_64" ]]; then
  echo "ChESSPIT currently accepts x86-64 engine binaries and requires an x86-64 VPS." >&2
  exit 1
fi
for command in docker openssl curl getent; do
  if ! command -v "$command" >/dev/null; then
    echo "Missing required command: $command" >&2
    exit 1
  fi
done
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required. Install Docker Engine with the Compose plugin and retry." >&2
  exit 1
fi

validate_domain() {
  local value="$1"
  [[ "$value" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] \
    && [[ "$value" == *.* ]] \
    && [[ "$value" != *..* ]]
}

domain=""
if [[ -f "$env_file" ]]; then
  if [[ "$(stat -c '%U:%a' "$env_file")" != "root:600" ]]; then
    echo "$env_file must be owned by root with mode 600." >&2
    exit 1
  fi
  # This file is generated by this script and contains only simple values.
  # shellcheck source=/dev/null
  . "$env_file"
  domain="${DOMAIN:-}"
fi

ssh_port="${ssh_port_override:-${SSH_PORT:-}}"
if [[ -z "$ssh_port" && -n "${SSH_CONNECTION:-}" ]]; then
  read -r _ _ _ ssh_port <<< "$SSH_CONNECTION"
fi
ssh_port="${ssh_port:-22}"
if [[ ! "$ssh_port" =~ ^[0-9]+$ ]] || (( ssh_port < 1 || ssh_port > 65535 )); then
  echo "SSH port must be an integer from 1 to 65535." >&2
  exit 1
fi
external_caddy="${external_caddy_override:-${EXTERNAL_CADDY:-false}}"
if [[ "$external_caddy" != "true" && "$external_caddy" != "false" ]]; then
  echo "EXTERNAL_CADDY must be true or false." >&2
  exit 1
fi
http_port="${http_port_override:-${CHESSPIT_HTTP_PORT:-3000}}"
if [[ ! "$http_port" =~ ^[0-9]+$ ]] || (( http_port < 1 || http_port > 65535 )); then
  echo "ChESSPIT HTTP port must be an integer from 1 to 65535." >&2
  exit 1
fi
if [[ -z "$domain" ]]; then
  read -r -p "Public domain (already pointing to this VPS): " domain
fi
domain="${domain,,}"
if ! validate_domain "$domain"; then
  echo "Enter a hostname such as arena.example.com (without https:// or a path)." >&2
  exit 1
fi
if ! getent ahosts "$domain" >/dev/null; then
  echo "$domain does not resolve in DNS yet. Point it to this VPS and retry." >&2
  exit 1
fi

install -d -o root -g root -m 0700 "$secret_dir"
if [[ ! -f "$env_file" ]]; then
  postgres_password="$(openssl rand -hex 32)"
  secret_key="$(openssl rand -hex 48)"
  umask 077
  printf '%s\n' \
    "DOMAIN=$domain" \
    "POSTGRES_PASSWORD=$postgres_password" \
    "SECRET_KEY=$secret_key" \
    "CHESSPIT_SECRETS_DIR=$secret_dir" \
    "TRUSTED_PROXIES=172.16.0.0/12" \
    "SSH_PORT=$ssh_port" \
    "EXTERNAL_CADDY=$external_caddy" \
    "CHESSPIT_BIND_ADDRESS=127.0.0.1" \
    "CHESSPIT_HTTP_PORT=$http_port" \
    > "$env_file"
  chmod 600 "$env_file"
  chown root:root "$env_file"
else
  set_env_value() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$env_file"; then
      sed -i "s/^${key}=.*/${key}=${value}/" "$env_file"
    else
      printf '%s=%s\n' "$key" "$value" >> "$env_file"
    fi
  }
  if [[ -n "$ssh_port_override" ]]; then
    set_env_value SSH_PORT "$ssh_port"
  fi
  if [[ -n "$external_caddy_override" ]]; then
    set_env_value EXTERNAL_CADDY "$external_caddy"
    set_env_value CHESSPIT_BIND_ADDRESS 127.0.0.1
  fi
  if [[ -n "$http_port_override" ]]; then
    set_env_value CHESSPIT_HTTP_PORT "$http_port"
  fi
fi

prompt_password() {
  local label="$1" first second
  while true; do
    read -r -s -p "$label password (minimum 12 characters): " first
    echo
    read -r -s -p "Confirm $label password: " second
    echo
    if [[ ${#first} -lt 12 ]]; then
      echo "Password must contain at least 12 characters." >&2
    elif [[ "$first" != "$second" ]]; then
      echo "Passwords did not match; try again." >&2
    else
      printf '%s' "$first"
      return
    fi
  done
}

arena_hash_file="$secret_dir/arena_password_hash"
admin_hash_file="$secret_dir/admin_password_hash"
if [[ "$rotate_passwords" == true || ! -s "$arena_hash_file" || ! -s "$admin_hash_file" ]]; then
  echo "Building the password hasher image..."
  docker build --target api -t chesspit-api:bootstrap "$project_dir"
  arena_password="$(prompt_password "Arena")"
  admin_password="$(prompt_password "Admin")"
  if [[ "$arena_password" == "$admin_password" ]]; then
    unset arena_password admin_password
    echo "Arena and admin passwords must be different." >&2
    exit 1
  fi
  hash_command='import sys; from argon2 import PasswordHasher; value=sys.stdin.buffer.read().decode(); print(PasswordHasher().hash(value))'
  arena_hash="$(printf '%s' "$arena_password" | docker run --rm -i --entrypoint python chesspit-api:bootstrap -c "$hash_command")"
  admin_hash="$(printf '%s' "$admin_password" | docker run --rm -i --entrypoint python chesspit-api:bootstrap -c "$hash_command")"
  unset arena_password admin_password
  umask 077
  printf '%s\n' "$arena_hash" > "$arena_hash_file"
  printf '%s\n' "$admin_hash" > "$admin_hash_file"
fi
# Docker Compose bind-mounts these files into a non-root API process. The
# containing directory remains root-only, so host users cannot traverse it.
chown root:root "$arena_hash_file" "$admin_hash_file"
chmod 644 "$arena_hash_file" "$admin_hash_file"

cd "$project_dir"
docker compose config --quiet
compose_args=()
up_args=(up -d --build --remove-orphans)
if [[ "$external_caddy" == "true" ]]; then
  # Free ports 80/443 when switching an existing deployment from the bundled
  # proxy. The stopped container is retained and can be started again later.
  docker compose --profile bundled-caddy stop caddy
else
  compose_args+=(--profile bundled-caddy)
fi
docker compose "${compose_args[@]}" "${up_args[@]}"

health=""
for _ in $(seq 1 60); do
  if health="$(curl -fsS --max-time 10 --resolve "$domain:443:127.0.0.1" "https://$domain/api/health" 2>/dev/null)" \
      && [[ "$health" == *'"sandbox":"ready"'* ]] \
      && [[ "$health" == *'"stockfish":true'* ]] \
      && [[ "$health" == *'"fastchess":true'* ]]; then
    break
  fi
  sleep 2
done
if [[ "$health" != *'"sandbox":"ready"'* ]]; then
  docker compose ps >&2
  if [[ "$external_caddy" == "true" ]]; then
    docker compose logs --tail=100 runner api web >&2
  else
    docker compose logs --tail=100 runner api web caddy >&2
  fi
  echo "Deployment did not become healthy. Check DNS and the logs above." >&2
  exit 1
fi

echo
echo "ChESSPIT is ready at https://$domain"
echo "Recorded host SSH port: $ssh_port (the installer does not reconfigure sshd or the host firewall)."
if [[ "$external_caddy" == "true" ]]; then
  echo "Using the host Caddy import; Docker web is available only at 127.0.0.1:$http_port."
fi
echo "Uploaded engines run only in the isolated, networkless runner container."
echo "The arena and admin passwords were not stored in plaintext."
