#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd "$(dirname "$0")/.." && pwd)"
rotate_passwords=false
ssh_port_override=""
external_caddy_override=""
http_port_override=""
engine_override=""

usage() {
  echo "Usage: sudo ./scripts/install-vps.sh [--engine docker|podman] [--rotate-passwords] [--ssh-port PORT] [--http-port PORT] [--external-caddy|--bundled-caddy]" >&2
}

while (( $# )); do
  case "$1" in
    --engine)
      if [[ -z "${2:-}" ]]; then
        usage
        exit 2
      fi
      engine_override="$2"
      shift 2
      ;;
    --rotate-passwords)
      rotate_passwords=true
      shift
      ;;
    --ssh-port)
      if [[ -z "${2:-}" ]]; then
        usage
        exit 2
      fi
      ssh_port_override="$2"
      shift 2
      ;;
    --external-caddy)
      external_caddy_override=true
      shift
      ;;
    --http-port)
      if [[ -z "${2:-}" ]]; then
        usage
        exit 2
      fi
      http_port_override="$2"
      shift 2
      ;;
    --bundled-caddy)
      external_caddy_override=false
      shift
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done
engine="${engine_override:-${ENGINE:-docker}}"
if [[ "$engine" != "docker" && "$engine" != "podman" ]]; then
  echo "ENGINE must be docker or podman." >&2
  exit 1
fi
rootless=false
if (( EUID != 0 )); then
  if [[ "$engine" != "podman" ]]; then
    echo "Run this installer with sudo." >&2
    exit 1
  fi
  rootless=true
fi
if [[ "$rootless" == true ]]; then
  config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/chesspit"
  secret_dir="$config_dir"
  env_file="$config_dir/.env"
else
  secret_dir="/etc/chesspit"
  env_file="$project_dir/.env"
fi
if [[ "$(uname -m)" != "x86_64" ]]; then
  echo "ChESSPIT currently accepts x86-64 engine binaries and requires an x86-64 VPS." >&2
  exit 1
fi
for command in "$engine" openssl curl getent; do
  if ! command -v "$command" >/dev/null; then
    echo "Missing required command: $command" >&2
    exit 1
  fi
done

engine_run() {
  "$engine" "$@"
}

compose_env_args=()

compose() {
  "$engine" compose "${compose_env_args[@]}" "$@"
}

if [[ "$engine" == "docker" ]]; then
  if ! docker compose version >/dev/null 2>&1; then
    echo "Docker Compose v2 is required. Install Docker Engine with the Compose plugin and retry." >&2
    exit 1
  fi
else
  compose_version="$(podman compose version 2>&1 || true)"
  if [[ "$compose_version" == *"podman-compose"* \
    || ( "$compose_version" != *"Docker Compose version"* \
      && "$compose_version" != *"docker-compose version"* ) ]]; then
    echo "Podman needs the docker-compose v2 provider; podman-compose does not support the Compose features this stack uses." >&2
    echo "Install the docker-compose v2 binary (or the Compose plugin) so that 'podman compose' selects it, then retry." >&2
    exit 1
  fi
fi

if [[ "$rootless" == true ]]; then
  # The runner image maps container UID/GID 10001, so the rootless user needs a
  # subordinate range wide enough to cover it.
  for id_file in /etc/subuid /etc/subgid; do
    range="$(awk -F: -v user="$(id -un)" -v uid="$(id -u)" \
      '$1 == user || $1 == uid {print $3; exit}' "$id_file" 2>/dev/null || true)"
    if [[ -z "$range" ]]; then
      echo "No $id_file range for $(id -un). Add one, for example: sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $(id -un)" >&2
      exit 1
    fi
    if [[ ! "$range" =~ ^[0-9]+$ ]] || (( range < 65536 )); then
      echo "The $id_file range for $(id -un) is only $range wide; ChESSPIT needs at least 65536." >&2
      exit 1
    fi
  done
  if [[ -z "${DOCKER_HOST:-}" ]]; then
    podman_socket="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/podman/podman.sock"
    if [[ ! -S "$podman_socket" ]]; then
      systemctl --user start podman.socket >/dev/null 2>&1 || true
    fi
    if [[ ! -S "$podman_socket" ]]; then
      echo "The rootless Podman API socket is missing. Start it with: systemctl --user enable --now podman.socket" >&2
      echo "Keep it available after logout with: loginctl enable-linger $(id -un)" >&2
      exit 1
    fi
    export DOCKER_HOST="unix://$podman_socket"
  fi
fi

validate_domain() {
  local value="$1"
  [[ "$value" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] \
    && [[ "$value" == *.* ]] \
    && [[ "$value" != *..* ]]
}

expected_owner=root
if [[ "$rootless" == true ]]; then
  expected_owner="$(id -un)"
  compose_env_args+=(--env-file "$env_file")
fi

domain=""
if [[ -f "$env_file" ]]; then
  if [[ "$(stat -c '%U:%a' "$env_file")" != "$expected_owner:600" ]]; then
    echo "$env_file must be owned by $expected_owner with mode 600." >&2
    exit 1
  fi
  # This file is generated by this script and contains only simple values.
  # shellcheck source=/dev/null
  . "$env_file"
  domain="${DOMAIN:-}"
fi

ssh_port="${ssh_port_override:-${SSH_PORT:-}}"
if [[ -z "$ssh_port" && -n "${SSH_CONNECTION:-}" ]]; then
  read -r _ _ _ ssh_port <<< "$SSH_CONNECTION"
fi
ssh_port="${ssh_port:-22}"
if [[ ! "$ssh_port" =~ ^[0-9]+$ ]] || (( ssh_port < 1 || ssh_port > 65535 )); then
  echo "SSH port must be an integer from 1 to 65535." >&2
  exit 1
fi
external_caddy="${external_caddy_override:-${EXTERNAL_CADDY:-false}}"
if [[ "$external_caddy" != "true" && "$external_caddy" != "false" ]]; then
  echo "EXTERNAL_CADDY must be true or false." >&2
  exit 1
fi
http_port="${http_port_override:-${CHESSPIT_HTTP_PORT:-3000}}"
if [[ ! "$http_port" =~ ^[0-9]+$ ]] || (( http_port < 1 || http_port > 65535 )); then
  echo "ChESSPIT HTTP port must be an integer from 1 to 65535." >&2
  exit 1
fi
if [[ "$rootless" == true && "$external_caddy" != "true" ]]; then
  echo "The bundled Caddy container binds ports 80 and 443, which rootless Podman cannot do." >&2
  echo "Terminate TLS with a host proxy and rerun with --external-caddy --http-port 9710." >&2
  exit 1
fi
if [[ -z "$domain" ]]; then
  read -r -p "Public domain (already pointing to this VPS): " domain
fi
domain="${domain,,}"
if ! validate_domain "$domain"; then
  echo "Enter a hostname such as arena.example.com (without https:// or a path)." >&2
  exit 1
fi
if ! getent ahosts "$domain" >/dev/null; then
  echo "$domain does not resolve in DNS yet. Point it to this VPS and retry." >&2
  exit 1
fi

if [[ "$rootless" == true ]]; then
  install -d -m 0700 "$secret_dir"
else
  install -d -o root -g root -m 0700 "$secret_dir"
fi
if [[ ! -f "$env_file" ]]; then
  postgres_password="$(openssl rand -hex 32)"
  secret_key="$(openssl rand -hex 48)"
  trusted_proxies="172.16.0.0/12"
  if [[ "$engine" == "podman" ]]; then
    trusted_proxies="10.89.0.0/16"
  fi
  trusted_proxies="${TRUSTED_PROXIES:-$trusted_proxies}"
  umask 077
  printf '%s\n' \
    "DOMAIN=$domain" \
    "POSTGRES_PASSWORD=$postgres_password" \
    "SECRET_KEY=$secret_key" \
    "CHESSPIT_SECRETS_DIR=$secret_dir" \
    "TRUSTED_PROXIES=$trusted_proxies" \
    "SSH_PORT=$ssh_port" \
    "EXTERNAL_CADDY=$external_caddy" \
    "CHESSPIT_BIND_ADDRESS=127.0.0.1" \
    "CHESSPIT_HTTP_PORT=$http_port" \
    > "$env_file"
  chmod 600 "$env_file"
  if [[ "$rootless" != true ]]; then
    chown root:root "$env_file"
  fi
else
  set_env_value() {
    local key="$1" value="$2"
    if grep -q "^${key}=" "$env_file"; then
      sed -i "s/^${key}=.*/${key}=${value}/" "$env_file"
    else
      printf '%s=%s\n' "$key" "$value" >> "$env_file"
    fi
  }
  if [[ -n "$ssh_port_override" ]]; then
    set_env_value SSH_PORT "$ssh_port"
  fi
  if [[ -n "$external_caddy_override" ]]; then
    set_env_value EXTERNAL_CADDY "$external_caddy"
    set_env_value CHESSPIT_BIND_ADDRESS 127.0.0.1
  fi
  if [[ -n "$http_port_override" ]]; then
    set_env_value CHESSPIT_HTTP_PORT "$http_port"
  fi
fi

read_secret() {
  local prompt="$1" outvar="$2" left="" right="" char rest
  if [[ ! -t 0 || ! -t 2 ]]; then
    IFS= read -r left
    printf -v "$outvar" '%s' "$left"
    return
  fi
  _redraw_secret() {
    local stars="" i
    for ((i = 0; i < ${#left} + ${#right}; i++)); do
      stars+='*'
    done
    printf '\r\033[K%s%s' "$prompt" "$stars" >&2
    for ((i = 0; i < ${#right}; i++)); do
      printf '\b' >&2
    done
  }
  _redraw_secret
  while IFS= read -r -s -n 1 char; do
    case "$char" in
      "")
        break
        ;;
      $'\033')
        rest=""
        IFS= read -r -s -n 1 -t 0.05 char || char=""
        case "$char" in
          '['|'O')
            while IFS= read -r -s -n 1 -t 0.05 char; do
              rest+="$char"
              [[ "$char" == [A-Za-z~] ]] && break
            done
            ;;
          *)
            continue
            ;;
        esac
        case "$rest" in
          D)  # left
            if [[ -n "$left" ]]; then
              right="${left: -1}$right"
              left="${left%?}"
            fi
            ;;
          C)  # right
            if [[ -n "$right" ]]; then
              left+="${right:0:1}"
              right="${right:1}"
            fi
            ;;
          H|1~|7~)  # home
            right="$left$right"
            left=""
            ;;
          F|4~|8~)  # end
            left+="$right"
            right=""
            ;;
          3~)  # delete
            right="${right:1}"
            ;;
          *)
            continue
            ;;
        esac
        ;;
      $'\177'|$'\b')  # backspace
        left="${left%?}"
        ;;
      $'\001')  # ctrl-a
        right="$left$right"
        left=""
        ;;
      $'\005')  # ctrl-e
        left+="$right"
        right=""
        ;;
      $'\002')  # ctrl-b
        if [[ -n "$left" ]]; then
          right="${left: -1}$right"
          left="${left%?}"
        fi
        ;;
      $'\006')  # ctrl-f
        if [[ -n "$right" ]]; then
          left+="${right:0:1}"
          right="${right:1}"
        fi
        ;;
      $'\004')  # ctrl-d
        right="${right:1}"
        ;;
      $'\013')  # ctrl-k
        right=""
        ;;
      $'\025')  # ctrl-u
        left=""
        ;;
      $'\027')  # ctrl-w
        left="${left%"${left##*[![:space:]]}"}"
        left="${left%"${left##*[[:space:]]}"}"
        ;;
      [[:cntrl:]])
        continue
        ;;
      *)
        left+="$char"
        ;;
    esac
    _redraw_secret
  done
  printf '\n' >&2
  unset -f _redraw_secret
  printf -v "$outvar" '%s' "$left$right"
}

prompt_password() {
  local label="$1" first second
  while true; do
    read_secret "$label password (minimum 12 characters): " first
    read_secret "Confirm $label password: " second
    if [[ ${#first} -lt 12 ]]; then
      echo "Password must contain at least 12 characters." >&2
    elif [[ "$first" != "$second" ]]; then
      echo "Passwords did not match; try again." >&2
    else
      printf '%s' "$first"
      return
    fi
  done
}

arena_hash_file="$secret_dir/arena_password_hash"
admin_hash_file="$secret_dir/admin_password_hash"
if [[ "$rotate_passwords" == true || ! -s "$arena_hash_file" || ! -s "$admin_hash_file" ]]; then
  echo "Building the password hasher image..."
  engine_run build --target api -t chesspit-api:bootstrap "$project_dir"
  arena_password="$(prompt_password "Arena")"
  admin_password="$(prompt_password "Admin")"
  if [[ "$arena_password" == "$admin_password" ]]; then
    unset arena_password admin_password
    echo "Arena and admin passwords must be different." >&2
    exit 1
  fi
  hash_command='import sys; from argon2 import PasswordHasher; value=sys.stdin.buffer.read().decode(); print(PasswordHasher().hash(value))'
  arena_hash="$(printf '%s' "$arena_password" | engine_run run --rm -i --entrypoint python chesspit-api:bootstrap -c "$hash_command")"
  admin_hash="$(printf '%s' "$admin_password" | engine_run run --rm -i --entrypoint python chesspit-api:bootstrap -c "$hash_command")"
  unset arena_password admin_password
  umask 077
  printf '%s\n' "$arena_hash" > "$arena_hash_file"
  printf '%s\n' "$admin_hash" > "$admin_hash_file"
fi
# Compose bind-mounts these files into a non-root API process. The containing
# directory stays owned by the installing identity alone, so other host users
# cannot traverse it.
if [[ "$rootless" != true ]]; then
  chown root:root "$arena_hash_file" "$admin_hash_file"
fi
chmod 644 "$arena_hash_file" "$admin_hash_file"

cd "$project_dir"
compose config --quiet
compose_args=()
up_args=(up -d --build --remove-orphans)
if [[ "$external_caddy" == "true" ]]; then
  # Free ports 80/443 when switching an existing deployment from the bundled
  # proxy. The stopped container is retained and can be started again later.
  compose --profile bundled-caddy stop caddy
else
  compose_args+=(--profile bundled-caddy)
fi
compose "${compose_args[@]}" "${up_args[@]}"

health_url="https://$domain/api/health"
health_args=(--resolve "$domain:443:127.0.0.1")
if [[ "$rootless" == true ]]; then
  # Rootless Podman never terminates TLS itself; probe the published loopback
  # port that the host proxy forwards to.
  health_url="http://127.0.0.1:$http_port/api/health"
  health_args=()
fi
health=""
for _ in $(seq 1 60); do
  if health="$(curl -fsS --max-time 10 "${health_args[@]}" "$health_url" 2>/dev/null)" \
      && [[ "$health" == *'"sandbox":"ready"'* ]] \
      && [[ "$health" == *'"stockfish":true'* ]] \
      && [[ "$health" == *'"fastchess":true'* ]]; then
    break
  fi
  sleep 2
done
if [[ "$health" != *'"sandbox":"ready"'* ]]; then
  compose ps >&2
  if [[ "$external_caddy" == "true" ]]; then
    compose logs --tail=100 runner api web >&2
  else
    compose logs --tail=100 runner api web caddy >&2
  fi
  echo "Deployment did not become healthy. Check DNS and the logs above." >&2
  exit 1
fi

if [[ "$engine" == "podman" ]]; then
  # Unlike dockerd, Podman has no daemon that re-applies Compose restart
  # policies after a reboot, so install a systemd unit that brings the stack up.
  podman_path="$(command -v podman)"
  service_scope=(--user)
  unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  unit_after="podman.socket"
  unit_wanted_by="default.target"
  if [[ "$rootless" != true ]]; then
    service_scope=(--system)
    unit_dir="/etc/systemd/system"
    unit_after="network-online.target"
    unit_wanted_by="multi-user.target"
  fi
  install -d -m 0755 "$unit_dir"
  unit_file="$unit_dir/chesspit.service"
  service_compose_args=("${compose_env_args[@]}" "${compose_args[@]}")
  {
    printf '%s\n' \
      "[Unit]" \
      "Description=ChESSPIT Compose stack (Podman)" \
      "After=$unit_after" \
      "Wants=$unit_after" \
      "" \
      "[Service]" \
      "Type=oneshot" \
      "RemainAfterExit=yes" \
      "TimeoutStartSec=0" \
      "WorkingDirectory=$project_dir" \
      "ExecStart=$podman_path compose ${service_compose_args[*]} up -d --remove-orphans" \
      "ExecStop=$podman_path compose ${service_compose_args[*]} down" \
      "" \
      "[Install]" \
      "WantedBy=$unit_wanted_by"
  } > "$unit_file"
  chmod 644 "$unit_file"
  if systemctl "${service_scope[@]}" daemon-reload >/dev/null 2>&1 \
      && systemctl "${service_scope[@]}" enable --now chesspit.service >/dev/null 2>&1; then
    service_summary="Enabled chesspit.service; manage the stack with 'systemctl ${service_scope[*]} status|restart|stop chesspit'."
  else
    echo "Wrote $unit_file but could not enable it automatically." >&2
    echo "Enable it manually with: systemctl ${service_scope[*]} enable --now chesspit.service" >&2
  fi
fi

echo
echo "ChESSPIT is ready at https://$domain"
echo "Recorded host SSH port: $ssh_port (the installer does not reconfigure sshd or the host firewall)."
if [[ "$external_caddy" == "true" ]]; then
  echo "Using the host Caddy import; the web service is available only at 127.0.0.1:$http_port."
fi
if [[ "$rootless" == true ]]; then
  echo "Rootless Podman deployment; configuration and hashes live in $secret_dir."
  echo "Run 'loginctl enable-linger $(id -un)' so the containers survive logout."
fi
if [[ -n "${service_summary:-}" ]]; then
  echo "$service_summary"
fi
echo "Uploaded engines run only in the isolated, networkless runner container."
echo "The arena and admin passwords were not stored in plaintext."
