#!/usr/bin/env bash
set -euo pipefail

project_dir="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$project_dir/.env"
secret_dir="/etc/chesspit"
rotate_passwords=false

usage() {
  echo "Usage: sudo ./scripts/install-vps.sh [--rotate-passwords]" >&2
}

if [[ "${1:-}" == "--rotate-passwords" ]]; then
  rotate_passwords=true
  shift
fi
if (( $# )); then
  usage
  exit 2
fi
if (( EUID != 0 )); then
  echo "Run this installer with sudo." >&2
  exit 1
fi
if [[ "$(uname -m)" != "x86_64" ]]; then
  echo "ChESSPIT currently accepts x86-64 engine binaries and requires an x86-64 VPS." >&2
  exit 1
fi
for command in docker openssl curl getent; do
  if ! command -v "$command" >/dev/null; then
    echo "Missing required command: $command" >&2
    exit 1
  fi
done
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required. Install Docker Engine with the Compose plugin and retry." >&2
  exit 1
fi

validate_domain() {
  local value="$1"
  [[ "$value" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] \
    && [[ "$value" == *.* ]] \
    && [[ "$value" != *..* ]]
}

domain=""
if [[ -f "$env_file" ]]; then
  if [[ "$(stat -c '%U:%a' "$env_file")" != "root:600" ]]; then
    echo "$env_file must be owned by root with mode 600." >&2
    exit 1
  fi
  # This file is generated by this script and contains only simple values.
  # shellcheck source=/dev/null
  . "$env_file"
  domain="${DOMAIN:-}"
fi
if [[ -z "$domain" ]]; then
  read -r -p "Public domain (already pointing to this VPS): " domain
fi
domain="${domain,,}"
if ! validate_domain "$domain"; then
  echo "Enter a hostname such as arena.example.com (without https:// or a path)." >&2
  exit 1
fi
if ! getent ahosts "$domain" >/dev/null; then
  echo "$domain does not resolve in DNS yet. Point it to this VPS and retry." >&2
  exit 1
fi

install -d -o root -g root -m 0700 "$secret_dir"
if [[ ! -f "$env_file" ]]; then
  postgres_password="$(openssl rand -hex 32)"
  secret_key="$(openssl rand -hex 48)"
  umask 077
  printf '%s\n' \
    "DOMAIN=$domain" \
    "POSTGRES_PASSWORD=$postgres_password" \
    "SECRET_KEY=$secret_key" \
    "CHESSPIT_SECRETS_DIR=$secret_dir" \
    "TRUSTED_PROXIES=172.16.0.0/12" \
    > "$env_file"
  chmod 600 "$env_file"
  chown root:root "$env_file"
fi

prompt_password() {
  local label="$1" first second
  while true; do
    read -r -s -p "$label password (minimum 12 characters): " first
    echo
    read -r -s -p "Confirm $label password: " second
    echo
    if [[ ${#first} -lt 12 ]]; then
      echo "Password must contain at least 12 characters." >&2
    elif [[ "$first" != "$second" ]]; then
      echo "Passwords did not match; try again." >&2
    else
      printf '%s' "$first"
      return
    fi
  done
}

arena_hash_file="$secret_dir/arena_password_hash"
admin_hash_file="$secret_dir/admin_password_hash"
if [[ "$rotate_passwords" == true || ! -s "$arena_hash_file" || ! -s "$admin_hash_file" ]]; then
  echo "Building the password hasher image..."
  docker build --target api -t chesspit-api:bootstrap "$project_dir"
  arena_password="$(prompt_password "Arena")"
  admin_password="$(prompt_password "Admin")"
  if [[ "$arena_password" == "$admin_password" ]]; then
    unset arena_password admin_password
    echo "Arena and admin passwords must be different." >&2
    exit 1
  fi
  hash_command='import sys; from argon2 import PasswordHasher; value=sys.stdin.buffer.read().decode(); print(PasswordHasher().hash(value))'
  arena_hash="$(printf '%s' "$arena_password" | docker run --rm -i --entrypoint python chesspit-api:bootstrap -c "$hash_command")"
  admin_hash="$(printf '%s' "$admin_password" | docker run --rm -i --entrypoint python chesspit-api:bootstrap -c "$hash_command")"
  unset arena_password admin_password
  umask 077
  printf '%s\n' "$arena_hash" > "$arena_hash_file"
  printf '%s\n' "$admin_hash" > "$admin_hash_file"
fi
# Docker Compose bind-mounts these files into a non-root API process. The
# containing directory remains root-only, so host users cannot traverse it.
chown root:root "$arena_hash_file" "$admin_hash_file"
chmod 644 "$arena_hash_file" "$admin_hash_file"

cd "$project_dir"
docker compose config --quiet
docker compose up -d --build --remove-orphans

health=""
for _ in $(seq 1 60); do
  if health="$(curl -fsS --max-time 10 --resolve "$domain:443:127.0.0.1" "https://$domain/api/health" 2>/dev/null)" \
      && [[ "$health" == *'"sandbox":"ready"'* ]] \
      && [[ "$health" == *'"stockfish":true'* ]] \
      && [[ "$health" == *'"fastchess":true'* ]]; then
    break
  fi
  sleep 2
done
if [[ "$health" != *'"sandbox":"ready"'* ]]; then
  docker compose ps >&2
  docker compose logs --tail=100 runner api web caddy >&2
  echo "Deployment did not become healthy. Check DNS and the logs above." >&2
  exit 1
fi

echo
echo "ChESSPIT is ready at https://$domain"
echo "Uploaded engines run only in the isolated, networkless runner container."
echo "The arena and admin passwords were not stored in plaintext."
